// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands.shooter;

import edu.wpi.first.wpilibj.command.InstantCommand;

import frc.robot.Robot;

/**
 *
 */
public class ShooterShootUsingCamera extends InstantCommand {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public ShooterShootUsingCamera() {

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.shooter);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize() {
		//System.out.println("ShooterShootUsingCamera: initialize");
		//double distance = Robot.camera!=null?Robot.camera.getDistanceToCompositeTargetUsingHorizontalFov():100;
		//double distance = Robot.camera!=null?Robot.camera.getFilteredDistanceToCompositeTarget():100;
		
		//double custom_rpm = Robot.camera!=null?3200.0+(distance-100)*10:3200;

		double verticalOffset = Robot.camera!=null?Robot.camera.getFilteredVerticalOffsetToCompositeTarget():10;

		double custom_rpm = 2.79 * verticalOffset * verticalOffset - 42.07 * verticalOffset + 3374.3;

		Robot.shooter.shootCustom(custom_rpm);
	}
}
