// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands.shooter;

import edu.wpi.first.wpilibj.command.TimedCommand;

import frc.robot.Robot;
import frc.robot.util.Magic;

/**
 *
 */
public class ShooterTimedShootUsingCamera extends TimedCommand {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public ShooterTimedShootUsingCamera(double timeout) {
		super(timeout);
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);
		requires(Robot.shooter);
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize() {
		//System.out.println("ShooterTimedShootUsingCamera: initialize");
		//double distance = Robot.camera!=null?Robot.camera.getDistanceToCompositeTargetUsingHorizontalFov():100;
		//double distance = Robot.camera!=null?Robot.camera.getFilteredDistanceToCompositeTarget():100;
		
		//double custom_rpm = Robot.camera!=null?3200.0+(distance-100)*10:3200;

		double verticalOffset = Robot.camera!=null?Robot.camera.getFilteredVerticalOffsetToCompositeTarget():10;

		double magic_rpm = Magic.getRpm(verticalOffset);

		Robot.shooter.shootCustom(magic_rpm);	
	}

	// Called repeatedly when this Command is scheduled to run
	@Override
	protected void execute() {
	}

	// Called once after timeout
	@Override
	protected void end() {
		System.out.println("ShooterTimedShootUsingCamera: end");
		Robot.shooter.stop();
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted() {
		System.out.println("ShooterTimedShootUsingCamera: interrupted");
		end();
	}
}
